name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build the project
        run: npm run build

      - name: Checkout gh-pages branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages

      - name: Remove old docs and copy new docs
        run: |
          rm -rf docs
          cp -r ../car-simulator/docs ./docs

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Deploy updated docs"
          git push origin gh-pages
